apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-appsets-test
spec:
  generators:
  - list:
      elements:
        - cluster: k3s-cluster2
          url: https://10.10.5.15:6443
          path: cluster/k3s-cluster2
        - cluster: k3s-cluster1
          url: https://10.10.10.5:6443
          path: cluster/k3s-cluster1
        - cluster: k3s-laptop
          url: https://192.168.1.5:6443
          path: cluster/k3s-laptop
  template:
    metadata:
      name: '{{cluster}}-apps'
    spec:
      project: default
      source:
        repoURL: https://github.com/deegbo/apps-appset.git
        targetRevision: main
        path: argocd-appsets/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: default
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
