apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: apache
    targetRevision: 11.3.4
    helm:
      valueFiles:
        - apache-values.yaml
  destination:
    server: https://1192.168.1.49:6443
    namespace: apache
  syncPolicy:
    automated: {}
