apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.12.1
    helm:
      valueFiles:
        - grafana-values.yaml
  destination:
    server: https://192.168.1.51:6443
    namespace: grafana
  syncPolicy:
    automated: {}
